<?php
use App\Models\Job;

// Clear existing just in case
Job::truncate();

$jobs = [
    // --- GOVERNMENT JOBS ---
    [
        'title' => 'Punjab Administrative Service (PAS) Officer',
        'description' => 'Recruitment for Administrative Officers under Punjab Public Service Commission (PPSC). Requires successful passing of PPSC Preliminary and Main examinations.',
        'company' => 'Punjab Public Service Commission (PPSC)',
        'location' => 'Chandigarh, Punjab',
        'type' => 'Full-time',
        'category' => 'govt',
        'salary_range' => '₹56,100 - ₹1,77,500/month',
        'deadline' => '2026-08-30',
    ],
    [
        'title' => 'Junior Electrical Engineer',
        'description' => 'Official vacancy for Junior Engineer (Electrical) at PSPCL. Tasks include network maintenance and managing local load grids across districts.',
        'company' => 'Punjab State Power Corporation Ltd (PSPCL)',
        'location' => 'Patiala, Punjab',
        'type' => 'Full-time',
        'category' => 'govt',
        'salary_range' => '₹35,400 - ₹1,12,400/month',
        'deadline' => '2026-09-15',
    ],
    [
        'title' => 'Punjab Police Sub-Inspector (SI)',
        'description' => 'Official recruitment for Sub-Inspectors in District Police and Armed Police cadres. Eligibility requires a degree and passing physical screening tests (PST).',
        'company' => 'Punjab Police Department',
        'location' => 'All Districts, Punjab',
        'type' => 'Full-time',
        'category' => 'govt',
        'salary_range' => '₹35,400/month basic pay',
        'deadline' => '2026-07-20',
    ],
    [
        'title' => 'Assistant Station Master (ASM)',
        'description' => 'Recruitment for Station Masters under Indian Railways (Northern Zone). Requires passing the RRB Computer Based Test (CBT) and Aptitude Test.',
        'company' => 'Northern Railway / RRB',
        'location' => 'Amritsar, Punjab',
        'type' => 'Full-time',
        'category' => 'govt',
        'salary_range' => '₹35,400 - ₹1,12,400/month',
        'deadline' => '2026-10-05',
    ],

    // --- PRIVATE SECTOR JOBS ---
    [
        'title' => 'Associate Software Engineer',
        'description' => 'Full-stack development using React, Node.js and cloud systems. Direct campus-hiring opportunity aligned with Mohali IT hub companies.',
        'company' => 'Infosys Mohali IT Park',
        'location' => 'Mohali, Punjab',
        'type' => 'Full-time',
        'category' => 'private',
        'salary_range' => '₹4,50,000 - ₹6,50,000/year',
        'deadline' => '2026-08-10',
    ],
    [
        'title' => 'Human Resource (HR) Specialist',
        'description' => 'Join one of the largest conglomerate textile corporations. Responsible for talent acquisition, employer branding and industrial relations.',
        'company' => 'Trident Group India',
        'location' => 'Ludhiana, Punjab',
        'type' => 'Full-time',
        'category' => 'private',
        'salary_range' => '₹5,00,000 - ₹8,00,000/year',
        'deadline' => '2026-08-25',
    ],
    [
        'title' => 'Operations Manager',
        'description' => 'Oversee manufacturing floor operations, inventory logistics, and worker scheduling at Ludhiana industrial unit.',
        'company' => 'Vardhman Textiles Ltd',
        'location' => 'Ludhiana, Punjab',
        'type' => 'Full-time',
        'category' => 'private',
        'salary_range' => '₹6,00,000 - ₹9,50,000/year',
        'deadline' => '2026-09-30',
    ],

    // --- SELF EMPLOYMENT & GOVT SCHEMES ---
    [
        'title' => 'NABARD Dairy Farming Subsidy Scheme',
        'description' => 'NABARD backed financial scheme for setting up modern dairy farming units in Punjab. Offers up to 25% subsidy (33.33% for SC/ST farmers) on unit setup.',
        'company' => 'NABARD / Punjab Dairy Development Board',
        'location' => 'Ludhiana, Punjab',
        'type' => 'Self-Employment Scheme',
        'category' => 'self-employment',
        'salary_range' => 'Financial Subsidy up to ₹3,00,000',
        'deadline' => '2026-12-31',
    ],
    [
        'title' => 'PMEGP Business Expansion Loan',
        'description' => 'Prime Minister\'s Employment Generation Programme offers bank-financed loans with subsidy of up to 35% for starting or expanding micro-manufacturing enterprises.',
        'company' => 'KVIB / District Industries Centre (DIC)',
        'location' => 'Jalandhar, Punjab',
        'type' => 'Startup Scheme',
        'category' => 'self-employment',
        'salary_range' => 'Project Loans up to ₹50,00,000',
        'deadline' => '2026-12-15',
    ],
    [
        'title' => 'Beekeeping & Honey Production Scheme',
        'description' => 'Agro-processing subsidy and tools kit scheme sponsored by Punjab Agro Industries. Includes free certified training at Punjab Agricultural University.',
        'company' => 'Punjab Agro Industries Corporation',
        'location' => 'Amritsar, Punjab',
        'type' => 'Agro-Business Scheme',
        'category' => 'self-employment',
        'salary_range' => 'Training + Support up to ₹1,50,000',
        'deadline' => '2026-11-30',
    ],

    // --- FOREIGN PLACEMENTS ---
    [
        'title' => 'Agricultural Business Associate',
        'description' => 'Verified international agricultural crop specialist vacancy. Recruitment facilitated by government certified overseas employment cell.',
        'company' => 'AgroCrop Canada Inc.',
        'location' => 'Saskatchewan, Canada (Visa Sponsored)',
        'type' => 'Full-time',
        'category' => 'foreign',
        'salary_range' => '$48,000 - $55,000 CAD/year',
        'deadline' => '2026-11-15',
    ],
    [
        'title' => 'Registered Staff Nurse (NHS)',
        'description' => 'Verified clinical care nurse positions in NHS Trust Hospitals. Relocation package, CBT visa training support and housing assistance provided.',
        'company' => 'NHS England / Overseas Cell',
        'location' => 'Birmingham, UK (Relocation Support)',
        'type' => 'Full-time',
        'category' => 'foreign',
        'salary_range' => '£28,400 - £34,500/year',
        'deadline' => '2026-09-01',
    ],
    [
        'title' => 'Hospitality & Culinary Associate',
        'description' => 'Direct placement drive under government collaborative visa program. Relocation and intensive German language training provided before departure.',
        'company' => 'Munich Grand Plaza Hotel',
        'location' => 'Munich, Germany',
        'type' => 'Full-time',
        'category' => 'foreign',
        'salary_range' => '€2,400 - €3,100/month',
        'deadline' => '2026-10-31',
    ],
    [
        'title' => 'Mega Job Mela Ludhiana 2026',
        'description' => 'Participate in the upcoming state-level mega job fair. Direct walk-in recruitment drive with 25+ top-tier private employers offering immediate interview sessions and on-spot placement offers.',
        'company' => 'District Bureau of Employment and Enterprises (DBEE)',
        'location' => 'DBEE Ludhiana Office, Ludhiana',
        'type' => 'Walk-in Hiring Drive',
        'category' => 'private',
        'salary_range' => '₹15,000 - ₹35,000/month',
        'deadline' => '2026-08-15',
    ],
    [
        'title' => 'Graduate Engineer Apprentice',
        'description' => 'Apprenticeship placement under National Apprenticeship Promotion Scheme (NAPS). Work under senior grid engineers, inspect substations, and get certified by DBEE and NAPS.',
        'company' => 'PSPCL / NAPS Training Scheme',
        'location' => 'Patiala, Punjab',
        'type' => 'Apprenticeship (NAPS)',
        'category' => 'govt',
        'salary_range' => '₹12,500/month stipend',
        'deadline' => '2026-09-30',
    ],
    [
        'title' => 'Certified Web Developer Training Course',
        'description' => 'Fully government-sponsored, free 3-month certification course in full-stack web development. Includes placement support and training from expert developers at DBEE center.',
        'company' => 'Skill India / Punjab Skill Development Mission (PSDM)',
        'location' => 'Mohali, Punjab',
        'type' => 'Free Certified Course',
        'category' => 'self-employment',
        'salary_range' => '100% Free Training + Tool Kit',
        'deadline' => '2026-10-15',
    ],
    [
        'title' => 'Freelance Graphic Designer',
        'description' => 'Design high-quality marketing collaterals, digital banners, and annual agro product brochures on a contract basis for Punjab government export promotion drives.',
        'company' => 'Punjab Agro Export Corporation',
        'location' => 'Remote / Work from Home',
        'type' => 'Contract / Freelance',
        'category' => 'private',
        'salary_range' => '₹25,000 - ₹35,000/project',
        'deadline' => '2026-08-20',
    ],
    [
        'title' => 'Overseas Free Study Scholarship Scheme',
        'description' => 'Government-sponsored fully-funded scholarship program for higher education abroad. Provides full tuition fee reimbursement and living expense allowance of up to ₹20,00,000 for selected post-graduate students in accredited international universities.',
        'company' => 'Punjab Overseas Employment Promotion Cell (POEPC)',
        'location' => 'Punjab & Selected Foreign Universities',
        'type' => 'Fully-Funded Scholarship',
        'category' => 'foreign',
        'salary_range' => 'Funding up to ₹20,00,000',
        'deadline' => '2026-10-15',
    ],
    [
        'title' => 'Indian Army Agniveer Induction Rally 2026',
        'description' => 'Official recruitment rally for the induction of Agniveers into the Indian Army (General Duty cadre). Open to physical screening tests (PST), running, and medical examinations.',
        'company' => 'Indian Army Recruiting Board / DBEE Punjab',
        'location' => 'Jalandhar Cantonment Rally Ground, Punjab',
        'type' => 'Recruitment Induction Rally',
        'category' => 'govt',
        'salary_range' => '₹30,000 - ₹40,000/month stipend',
        'deadline' => '2026-08-30',
    ],
];

foreach ($jobs as $job) {
    Job::create($job);
}

echo "Successfully seeded " . count($jobs) . " real PGRKAM jobs and schemes!\n";
